export const cities = [
    { id: 1, cityEn: "Addis Ababa", cityDk: "Addis Abeba" },
    { id: 2, cityEn: "Bahr el Ghazal", cityDk: "Bahr el Ghazal" },
    { id: 3, cityEn: "Cairo", cityDk: "Cairo" },
    { id: 4, cityEn: "Dakar", cityDk: "Dakar" },
    { id: 5, cityEn: "Darfur", cityDk: "Darfur" },
    { id: 6, cityEn: "Dragon Mountains", cityDk: "Drakbergen" },
    { id: 7, cityEn: "Gold Coast", cityDk: "Guldkysten" },
    { id: 8, cityEn: "Kabalo", cityDk: "Kabalo" },
    { id: 9, cityEn: "Canary Islands", cityDk: "De Kanariske Øer" },
    { id: 10, cityEn: "Walvis Bay", cityDk: "Hvalbugten" },
    { id: 11, cityEn: "Cape Guardafui", cityDk: "Kap Guardafui" },
    { id: 12, cityEn: "Cape St. Marie", cityDk: "Kap St. Marie" },
    { id: 13, cityEn: "Cape Town", cityDk: "Kapstaden" },
    { id: 14, cityEn: "Congo", cityDk: "Kongo" },
    { id: 15, cityEn: "Luanda", cityDk: "Luanda" },
    { id: 16, cityEn: "Marrakech", cityDk: "Marrakech" },
    { id: 17, cityEn: "Mozambique", cityDk: "Moçambique" },
    { id: 18, cityEn: "Omdurman", cityDk: "Omdurman" },
    { id: 19, cityEn: "Sahara", cityDk: "Sahara" },
    { id: 20, cityEn: "Saint Helena", cityDk: "Sankta Helena" },
    { id: 21, cityEn: "Sierra Leone", cityDk: "Sierra Leone" },
    { id: 22, cityEn: "Bight of Benin", cityDk: "Beninbugten" },
    { id: 23, cityEn: "Suakin", cityDk: "Suakin" },
    { id: 24, cityEn: "Tamatave", cityDk: "Tamatave" },
    { id: 25, cityEn: "Tangier", cityDk: "Tangen" },
    { id: 26, cityEn: "Timbuktu", cityDk: "Timbuktu" },
    { id: 27, cityEn: "Tripoli", cityDk: "Tripolis" },
    { id: 28, cityEn: "Tunis", cityDk: "Tunis" },
    { id: 29, cityEn: "Victoria Falls", cityDk: "Victoriafaldet" },
    { id: 30, cityEn: "Lake Victoria", cityDk: "Victoriasøen" },
    { id: 31, cityEn: "Wadai", cityDk: "Wadai" },
    { id: 32, cityEn: "Zanzibar", cityDk: "Zanzibar" },
    { id: 33, cityEn: "Tangiers", cityDk: "Tangiers" },
    { id: 34, cityEn: "Slave Coast", cityDk: "Slave kysten" },
  ];